---

internet-rtr01:
    hostname: 10.10.20.181
    platform: ios
    site: devnet_sandbox
    groups:
        - devnet-cml-lab

edge-sw01:
    hostname: 10.10.20.172
    platform: ios
    site: devnet_sandbox
    groups:
        - devnet-cml-lab
    data:
        role: edge-switch

core-rtr01:
    hostname: 10.10.20.173
    platform: iosxr
    groups:
        - devnet-cml-lab
    data:
        role: core-router

core-rtr02:
    hostname: 10.10.20.174
    platform: iosxr
    groups:
        - devnet-cml-lab
    data:
        role: core-router

dist-rtr01:
    hostname: 10.10.20.175
    platform: ios
    groups:
        - devnet-cml-lab
    data:
        role: distribution-router

dist-rtr02:
    hostname: 10.10.20.176
    platform: ios
    groups:
        - devnet-cml-lab
    data:
        role: distribution-router

dist-sw01:
    hostname: 10.10.20.177
    platform: nxos_ssh
    transport: ssh
    groups:
        - devnet-cml-lab
    data:
        role: distribution-switch

dist-sw02:
    hostname: 10.10.20.178
    platform: nxos_ssh
    transport: ssh
    groups:
        - devnet-cml-lab
    data:
        role: distribution-switch

